import { Inter } from "next/font/google";
import "./globals.css";

import  "/public/css/bootstrap.min.css";
import  "/public/css/venobox.min.css";
import  "/public/css/swiper.min.css";

import  "/public/css/banner.css";
import  "/public/css/main.css";
import  "/public/css/bannernew.css";
import  "/public/css/responsive1920.css";
import  "/public/css/tablet.css";



import Header from "@/components/Header";
import Link from "next/link";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Asian Dispatch",
  description: "Generated by Asian Dispatch",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Header />
        {children}
        <Footer />





        <script src="js/jquary-3.6.0.min.js"></script>

        <script src="js/bootstrap.min.js"></script>
        <script src="js/popper.min.js"></script>
        <script src="js/venobox.min.js"></script>
        <script src="js/swiper.min.js"></script>
        <script src="js/smooth-scroll.js"></script>
        <script src="js/mailchimp.js"></script>
        <script src="js/main.js"></script>


        <script src="js/most-popular.js"></script>
      </body>
    </html>
  );
}
