import { Inter } from "next/font/google";
import "./globals.css";


import "./css/bootstrap.min.css";
import "./css/venobox.min.css";
import "./css/swiper.min.css";
import "./css/most-popular.css";
import "./css/banner.css";
import "./css/main.css";
import "./css/bannernew.css";



import Header from "@/components/Header";
import Link from "next/link";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Asian Dispatch",
  description: "Generated by Asian Dispatch",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Header />
        {children}
        <Footer />





        <script src="js/jquary-3.6.0.min.js"></script>

        <script src="js/bootstrap.min.js"></script>
        <script src="js/popper.min.js"></script>
        <script src="js/venobox.min.js"></script>
        <script src="js/swiper.min.js"></script>
        <script src="js/smooth-scroll.js"></script>
        <script src="js/mailchimp.js"></script>
        <script src="js/main.js"></script>


        <script src="js/most-popular.js"></script>
      </body>
    </html>
  );
}
